name: build

on:
  schedule:
    - cron: '0 16 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest package version from PyPI
        id: version
        run: |
          VERSION=$(python -c "import urllib.request, json;data = json.load(urllib.request.urlopen('https://pypi.org/pypi/aktools/json'));print(data['info']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aktools:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/aktools:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/aktools:latest
          cache-to: type=inline
